name: size_follower
description: "A widget that follows the size of another widget (on a one-frame delay)."
version: 1.0.0
license: MIT
homepage: https://github.com/makoConstruct/size_follower
environment:
  sdk: ^3.6.2
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter: